server:
  port: 8078

spring:
  application:
    name: keycloak-auth-service
  #  datasource:
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    url: jdbc:sqlserver://52.4.172.195;instance=;DatabaseName=EpayDatabase;trustServerCertificate=true;
  #    username: sa
  #    password: "%$Afro123"
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ec2-54-211-210-11.compute-1.amazonaws.com/:7080/realms/OnlineResourceHub
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


keycloak:
  token-uri: http://ec2-54-211-210-11.compute-1.amazonaws.com:7080/realms/OnlineResourceHub/protocol/openid-connect/token
  grant-type: password
  client-id: OnlineResourceHub
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
  realm-base-url: http://ec2-54-211-210-11.compute-1.amazonaws.com:7080/realms/OnlineResourceHub
  masterUrl: http://ec2-54-211-210-11.compute-1.amazonaws.com:7080/realms/master/protocol/openid-connect/token
  client-user-uri: http://ec2-54-211-210-11.compute-1.amazonaws.com:7080/realms/OnlineResourceHub/users
  client-uuid: 60cbfeb0-14a7-484c-863d-45ab7c370aee

api-urls:
  frontend-login-link: http://44.196.149.62:4200
notifications:
  service-url: http://localhost:8082/notifications/send-notifications
  jwt:
    auth:
      converter:
        resource-id: OnlineResourceHub
        principal-attribute: preferred_username
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://44.196.149.62:8445/eureka/
