server:
  port: 8078

spring:
  application:
    name: user-management-service
  #  datasource:
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    url: jdbc:sqlserver://52.4.172.195;instance=;DatabaseName=EpayDatabase;trustServerCertificate=true;
  #    username: sa
  #    password: "%$Afro123"
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://44.196.149.62:8080/realms/test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

api-urls:
  frontend-login-link: http://44.196.149.62:4200
keycloak:
  token-uri: http://44.196.149.62:8080/realms/test/protocol/openid-connect/token
  grant-type: password
  client-id: OnlineResourceHub
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
  realm-base-url: http://44.196.149.62:8080/admin/realms/test
  masterUrl: http://44.196.149.62:8080/realms/master/protocol/openid-connect/token
  client-user-uri: http://44.196.149.62:8080/admin/realms/test/users
  client-uuid: 2a36dfb4-0912-4c35-b817-7d1926277644


notifications:
  service-url: http://localhost:8082/notifications/send-notifications
  jwt:
    auth:
      converter:
        resource-id: OnlineResourceHub
        principal-attribute: preferred_username
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://44.196.149.62:8445/eureka/
